import { Building2, KeyRound, PhoneCall, Save, ShieldCheck } from "lucide-react";
import { Status, Toggle, PageHeader, Field, Empty } from '../components/ui.jsx';
import { findActiveWorkspace } from '../activeWorkspace.js';

export function SystemPage({ config, setConfig, overview, onSave, onChangePassword, isSuperadmin }) {
  const { index: organizationIndex, organization } = findActiveWorkspace(config.organizations, config.activeOrganizationId);
  const updateOrganization = (change) => setConfig({ ...config, organizations: config.organizations.map((item, index) => index === organizationIndex ? { ...item, ...change } : item) });
  // Every field below writes to one customer's row. Without a row to write to
  // there is nothing safe to show: the first organization in the list is
  // someone else, and its account contact, billing email and extension range
  // were edited under the name of the customer the operator had opened.
  if (!organization) return <div className="page"><PageHeader eyebrow={isSuperadmin ? 'CUSTOMER SYSTEM' : 'COMPANY SETTINGS'} title={isSuperadmin ? 'Customer phone system' : 'Company settings'} subtitle="Settings are shown for the customer workspace that is open." />
    <Empty icon={Building2} title="This workspace is unavailable" copy="The open workspace is no longer in the customer list. Choose a customer again to edit its settings." /></div>;
  return <div className="page"><PageHeader eyebrow={isSuperadmin ? 'CUSTOMER SYSTEM' : 'COMPANY SETTINGS'} title={isSuperadmin ? 'Customer phone system' : 'Company settings'} subtitle={isSuperadmin ? 'Configure the selected customer workspace and its phone-system defaults.' : 'Manage the company identity and calling defaults available to your team.'}><button className="primary" onClick={onSave}><Save /> Save settings</button></PageHeader>
    <section className="band"><div className="section-title"><div><h2>{isSuperadmin ? 'Customer organization' : 'Company identity'}</h2><p>{isSuperadmin ? 'Identity and calling defaults for the selected Vocivo customer only.' : 'Company identity and defaults inherited by users and call routes.'}</p></div></div><div className="form-grid"><Field label={organization?.accountType === 'individual' ? 'Customer name' : 'Customer company name'}><input value={config.company.name} onChange={(e) => setConfig({ ...config, company: { ...config.company, name: e.target.value }, organizations: config.organizations.map((item, index) => index === organizationIndex ? { ...item, name: e.target.value } : item) })} /></Field>{isSuperadmin ? <Field label="Customer account type"><select value={organization?.accountType || 'business'} onChange={(e) => updateOrganization({ accountType: e.target.value, internalCallingEnabled: e.target.value === 'business' && organization.internalCallingEnabled })}><option value="business">Business customer</option><option value="individual">Individual customer</option></select></Field> : <Field label="Vocivo service"><input value={organization?.accountType === 'individual' ? 'Individual service' : 'Business customer'} readOnly /></Field>}<Field label={isSuperadmin ? 'Customer account contact' : 'Company account contact'}><input value={organization?.ownerDisplayName || ''} onChange={(e) => updateOrganization({ ownerDisplayName: e.target.value })} /></Field><Field label="Billing contact email"><input type="email" value={organization?.ownerEmail || ''} onChange={(e) => updateOrganization({ ownerEmail: e.target.value })} /></Field><Field label="Timezone"><input value={config.company.timezone} onChange={(e) => setConfig({ ...config, company: { ...config.company, timezone: e.target.value } })} /></Field><Field label="Default outbound caller ID"><input value={config.company.defaultCallerId} onChange={(e) => setConfig({ ...config, company: { ...config.company, defaultCallerId: e.target.value } })} /></Field></div></section>
    {isSuperadmin && organization?.accountType === 'business' && <section className="band"><div className="section-title"><div><h2>Internal extension allocation</h2><p>Reserve a private numberless calling range for this customer.</p></div><Status good={organization?.internalCallingEnabled}>{organization?.internalCallingEnabled ? 'Enabled' : 'Disabled'}</Status></div><div className="form-grid"><Field label="First extension" help="Two to five digits."><input type="number" min="10" max="99999" value={organization?.extensionStart ?? 2000} onChange={(e) => updateOrganization({ extensionStart: Number(e.target.value) })} /></Field><Field label="Last extension" help="The inclusive end of this company's allocation."><input type="number" min="10" max="99999" value={organization?.extensionEnd ?? 2019} onChange={(e) => updateOrganization({ extensionEnd: Number(e.target.value) })} /></Field></div><div className="setting-line"><div><strong>Internal extension calling</strong><span>Users in this company can dial extensions without a public phone number or PSTN charge.</span></div><Toggle value={organization?.internalCallingEnabled !== false} onChange={(internalCallingEnabled) => updateOrganization({ internalCallingEnabled })} /></div><div className="info-strip"><PhoneCall /><span>{organization ? `${organization.extensionEnd - organization.extensionStart + 1} private extension slots allocated from ${organization.extensionStart} to ${organization.extensionEnd}.` : 'Configure an organization range.'}</span></div></section>}
    {isSuperadmin && <section className="band"><div className="section-title"><div><h2>Platform infrastructure</h2><p>Carrier and production connection information is visible only to Vocivo superadmins.</p></div></div><div className="detail-grid"><div><span>Voice connection</span><strong>{overview?.connection?.name || 'Unavailable'}</strong></div><div><span>Connection status</span><strong>{overview?.connection?.active === null ? 'Not measured' : overview?.connection?.active ? 'Active' : 'Inactive'}</strong></div><div><span>Incoming iOS push</span><strong>{overview?.connection?.iosPushConfigured ? 'Configured' : 'Not configured'}</strong></div><div><span>Voice provider</span><strong>{overview?.connection?.provider === 'sip' ? 'Vocivo SIP' : overview?.connection?.provider === 'telnyx' ? 'Telnyx' : 'Unavailable'}</strong></div><div><span>Control plane</span><strong>{config.platform.controlPlane}</strong></div><div><span>SIP domain</span><strong>{overview?.connection?.sipDomain || 'Unavailable'}</strong></div><div><span>Configuration updated</span><strong>{new Date(config.updatedAt).toLocaleString()}</strong></div></div></section>}
    <section className="band"><div className="section-title"><div><h2>Administrator security</h2><p>Change the password for the currently signed-in {isSuperadmin ? 'Vocivo platform' : 'company administrator'} account.</p></div><button className="secondary" onClick={onChangePassword}><KeyRound /> Change password</button></div><div className="info-strip"><ShieldCheck /><span>Use at least 10 characters with upper and lowercase letters and a number.</span></div></section>
  </div>;
}
