applications/mod_commands
applications/mod_dptools
applications/mod_db
applications/mod_hash
applications/mod_curl
applications/mod_http_cache
applications/mod_expr
applications/mod_fifo
applications/mod_spandsp
applications/mod_voicemail
applications/mod_conference
codecs/mod_opus
codecs/mod_g723_1
codecs/mod_g729
codecs/mod_amr
codecs/mod_b64
endpoints/mod_sofia
endpoints/mod_loopback
event_handlers/mod_event_socket
event_handlers/mod_cdr_csv
event_handlers/mod_json_cdr
formats/mod_local_stream
formats/mod_native_file
formats/mod_sndfile
formats/mod_tone_stream
formats/mod_shout
loggers/mod_console
loggers/mod_logfile
say/mod_say_en
asr_tts/mod_flite
xml_int/mod_xml_curl
dialplans/mod_dialplan_xml
