import { useMemo, useState } from 'react';
import { Download, RefreshCw } from 'lucide-react';
import { PageHeader } from '../components/ui.jsx';
import { useOperations } from './useOperations';
import { reportCsv } from './report-export';
import './operations.css';
const day = (date: Date) => date.toISOString().slice(0, 10);
export function ReportsPage({ api }: { api: any }) {
  const [from, setFrom] = useState(() => day(new Date(Date.now() - 6 * 86400_000)));
  const [to, setTo] = useState(() => day(new Date()));
  const [timezone, setTimezone] = useState(() => Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC');
  const [search, setSearch] = useState(''); const [direction, setDirection] = useState('all'); const [status, setStatus] = useState('all'); const [page, setPage] = useState(0);
  const [query, setQuery] = useState(() => `/api/admin/reports?${new URLSearchParams({ from: `${from}T00:00:00Z`, to: `${day(new Date(Date.parse(to) + 86400_000))}T00:00:00Z`, timezone })}`);
  const { data, error, loading, refresh } = useOperations(api, query);
  const calls = useMemo(() => (data?.calls || []).filter((c: any) => (direction === 'all' || c.direction === direction) && (status === 'all' || c.status === status) && `${c.from} ${c.to} ${c.hangupCause}`.toLowerCase().includes(search.toLowerCase())), [data, direction, status, search]);
  const a = data?.analytics;
  function exportCalls() { const url = URL.createObjectURL(new Blob([reportCsv(calls)], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'vocivo-call-records.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  const pages = Math.max(1, Math.ceil(calls.length / 50)); const currentPage = Math.min(page, pages - 1);
  return <div className="page operations-page"><PageHeader eyebrow="CALL INTELLIGENCE" title="Reports" subtitle={data ? `${data.calls.length} distinct calls · ${data.timezone}` : 'Call records and wallet activity'}><button className="secondary" disabled={!data || loading} onClick={exportCalls}><Download /> Export CSV</button></PageHeader>
    <form className="ops-toolbar" onSubmit={e => { e.preventDefault(); setPage(0); setQuery(`/api/admin/reports?${new URLSearchParams({ from: `${from}T00:00:00Z`, to: new Date(Date.parse(to) + 86400_000).toISOString(), timezone })}`); refresh(); }}>
      <label>From (UTC)<input type="date" required value={from} onChange={e => setFrom(e.target.value)} /></label><label>Through (UTC)<input type="date" required value={to} onChange={e => setTo(e.target.value)} /></label>
      <label>Chart timezone<input value={timezone} required onChange={e => setTimezone(e.target.value)} /></label><button className="secondary" disabled={loading}><RefreshCw /> {loading ? 'Loading...' : 'Apply'}</button>
    </form>
    {error && <p role="alert" className="ops-notice">{error}</p>}{data && !data.complete && <p className="ops-notice" role="status">Partial report: the event limit was reached. Select a shorter date range.</p>}
    <div className="ops-metrics">{[['Calls', a?.total], ['Answered', a?.answered], ['Incomplete records', a?.incomplete], ['Talk minutes', a ? (a.durationSeconds / 60).toFixed(1) : null]].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value ?? '\u2014'}</strong></div>)}</div>
    <div className="ops-analysis"><section><h2>Calls by hour</h2><div className="ops-hours" aria-label="Calls by hour">{a?.hours.map((h: any) => <div key={h.hour} title={`${h.hour}:00 - ${h.calls} calls`}><b>{h.calls}</b><i style={{ height: `${Math.max(2, h.calls / Math.max(1, ...a.hours.map((v: any) => v.calls)) * 110)}px` }} /><small>{h.hour.toString().padStart(2, '0')}</small></div>)}</div></section><section><h2>Direction distribution</h2>{Object.entries(a?.directions || {}).map(([name, count]) => <div className="ops-summary-row" key={name}><span>{name}</span><strong>{String(count)}</strong></div>)}</section></div>
    <section><h2>Top extensions</h2><div className="ops-table"><table><thead><tr><th>Colleague</th><th>Extension</th><th>Calls</th><th>Answered</th><th>Talk minutes</th></tr></thead><tbody>{a?.topExtensions.map((u: any) => <tr key={u.id}><td>{u.name}</td><td>{u.extension}</td><td>{u.calls}</td><td>{u.answered}</td><td>{(u.seconds / 60).toFixed(1)}</td></tr>)}</tbody></table>{!a?.topExtensions.length && <p className="ops-empty">No extension activity in this range</p>}</div></section>
    <section><h2>Billing analysis</h2><p className="ops-note">Call charges: unreconciled ({a?.billing.unpricedCalls ?? '\u2014'} records). Wallet movements below are not carrier usage charges.</p>{data?.wallet.available ? <div className="ops-table"><table><thead><tr><th>Currency</th><th>Movement</th><th>Type</th><th>Entries</th><th>Amount (minor units)</th></tr></thead><tbody>{data.wallet.rows.map((r: any) => <tr key={`${r.currency}-${r.direction}-${r.type}`}><td>{r.currency}</td><td>{r.direction}</td><td>{r.type.replaceAll('_', ' ')}</td><td>{r.entries}</td><td>{r.amountMinor}</td></tr>)}</tbody></table>{!data.wallet.rows.length && <p className="ops-empty">No wallet movements in this range</p>}</div> : <p className="ops-note">Wallet reporting unavailable</p>}</section>
    <section><h2>Call records</h2><div className="ops-toolbar"><input type="search" placeholder="Search caller, colleague or cause" aria-label="Search call records" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /><select aria-label="Call direction" value={direction} onChange={e => { setDirection(e.target.value); setPage(0); }}>{['all', 'inbound', 'outbound', 'internal'].map(v => <option key={v} value={v}>{v === 'all' ? 'All directions' : v}</option>)}</select><select aria-label="Call status" value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}>{['all', 'answered', 'no_answer', 'busy', 'cancelled', 'failed', 'incomplete'].map(v => <option key={v} value={v}>{v.replaceAll('_', ' ')}</option>)}</select></div>
    <div className="ops-table"><table><thead><tr><th>Started</th><th>Direction</th><th>From</th><th>To</th><th>Status</th><th>Talk time</th><th>Hangup cause</th></tr></thead><tbody>{calls.slice(currentPage * 50, (currentPage + 1) * 50).map((c: any) => <tr key={c.id}><td>{new Date(c.startedAt).toLocaleString(undefined, { timeZone: data.timezone })}</td><td>{c.direction}</td><td>{c.from}</td><td>{c.to}</td><td>{c.status.replaceAll('_', ' ')}</td><td>{c.durationSeconds === null ? '\u2014' : `${c.durationSeconds}s`}</td><td>{c.hangupCause || '\u2014'}</td></tr>)}</tbody></table>{!calls.length && <p className="ops-empty">{loading ? 'Loading call records...' : 'No matching calls'}</p>}</div><div className="ops-toolbar"><button className="secondary" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Previous</button><span>{currentPage + 1} / {pages}</span><button className="secondary" disabled={currentPage + 1 >= pages} onClick={() => setPage(currentPage + 1)}>Next</button></div></section>
  </div>;
}
